title: "EcoNIbe"
description: "Ecological Niche Modelling in Iberia research group"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "default"
url: "https://alezarzo.github.io"
baseurl: "/econibe.github.io"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
